services:
  ib-gateway:
    image: ib-gateway
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        PROGRAM: ibgateway
        RELEASE: stable
        ARCH: x64
    container_name: gateway
    restart: always
    network_mode: host
    environment:
      # VNC is disabled unless VNC_PWD is set in .env.
      VNC_PWD: ${VNC_PWD:-}
      VNC_PORT: ${VNC_PORT:-5900}
      VNC_SCREEN_DIMENSION: ${VNC_SCREEN_DIMENSION:-1600x1200x24}
      # live or paper.
      TRADING_MODE: ${TRADING_MODE:-paper}
      ACCEPT_NON_BROKERAGE_WARNING: ${ACCEPT_NON_BROKERAGE_WARNING:-yes}
      READ_ONLY_API: ${READ_ONLY_API:-no}
      TIME_ZONE: ${TIME_ZONE:-America/New_York}
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
      COLD_RESTART_TIME: ${COLD_RESTART_TIME:-}
      BYPASS_WARNING: ${BYPASS_WARNING:-yes}
      SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-Every 30 mins}
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
      JAVA_HEAP_SIZE: ${JAVA_HEAP_SIZE:-}
      CUSTOM_JVM_OPTS: ${CUSTOM_JVM_OPTS:-}
      IB_USER: ${IB_USER}
      IB_PASSWORD: ${IB_PASSWORD}
  ib-tws:
    image: ib-tws
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        PROGRAM: tws
        RELEASE: stable
        ARCH: x64
    container_name: tws
    restart: always
    network_mode: host
    security_opt:
      - seccomp:unconfined
    shm_size: 2g
    environment:
      # VNC is disabled unless VNC_PWD is set in .env.
      VNC_PWD: ${VNC_PWD:-}
      VNC_PORT: ${TWS_VNC_PORT:-5901}
      VNC_SCREEN_DIMENSION: ${VNC_SCREEN_DIMENSION:-1600x1200x24}
      # live or paper.
      TRADING_MODE: ${TRADING_MODE:-paper}
      ACCEPT_NON_BROKERAGE_WARNING: ${ACCEPT_NON_BROKERAGE_WARNING:-yes}
      READ_ONLY_API: ${READ_ONLY_API:-no}
      TIME_ZONE: ${TIME_ZONE:-America/New_York}
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
      COLD_RESTART_TIME: ${COLD_RESTART_TIME:-}
      BYPASS_WARNING: ${BYPASS_WARNING:-yes}
      SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-Every 30 mins}
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
      JAVA_HEAP_SIZE: ${JAVA_HEAP_SIZE:-}
      CUSTOM_JVM_OPTS: ${CUSTOM_JVM_OPTS:-}
      IB_USER: ${IB_USER}
      IB_PASSWORD: ${IB_PASSWORD}
