services:
  ib-gateway:
    image: ib-gateway
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        PROGRAM: ibgateway
        RELEASE: stable
        ARCH: x64
    container_name: gateway
    restart: always
    network_mode: host
    environment:
      # VNC is disabled unless VNC_PWD is set in .env.
      VNC_PWD: ${VNC_PWD:-}
      VNC_SCREEN_DIMENSION: ${VNC_SCREEN_DIMENSION:-1600x1200x24}
      # live or paper.
      TRADING_MODE: ${TRADING_MODE:-paper}
      IB_USER: ${IB_USER}
      IB_PASSWORD: ${IB_PASSWORD}
  ib-tws:
    image: ib-tws
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        PROGRAM: tws
        RELEASE: stable
        ARCH: x64
    container_name: tws
    restart: always
    network_mode: host
    security_opt:
      - seccomp:unconfined
    shm_size: 2g
    environment:
      # VNC is disabled unless VNC_PWD is set in .env.
      VNC_PWD: ${VNC_PWD:-}
      VNC_SCREEN_DIMENSION: ${VNC_SCREEN_DIMENSION:-1600x1200x24}
      # live or paper.
      TRADING_MODE: ${TRADING_MODE:-paper}
      IB_USER: ${IB_USER}
      IB_PASSWORD: ${IB_PASSWORD}
